### ISSUE TITLE
Periodically update video title/description...

### ISSUE THREAD

**Issue by ivmilicevic** [rokudev/SceneGraphDeveloperExtensions#25]
Hello, we are building roku channel that is primarily focused on streaming of live TV channels. I'm wondering is there a way to retrieve information about current program from API while stream is playing, on some kind of timer(for example every minute or so) or on user interaction?

Current content handlers work great to fill that same information on transition from details screen to mediaview screen, but TV show playing can change and information displayed will be from previous show

**Comment by RokuChris** [comment]
The easiest way to make periodic API calls during playback is to use a BookmarkHandler. They are intended for doing things like heartbeat calls during playback, but you can do other things if you want. There's an example here: https://github.com/rokudev/SceneGraphDeveloperExtensions/tree/master/samples/9_Bookmarks

The other piece of your scenario is more difficult. Updating the metadata displayed in MediaView while content is playing is not supported in the current version of SGDEX. This is due to a limitation of the underlying Video node in Roku Scene Graph. We are looking into ways of supporting this in a future version. In the meantime, the best way to accomplish what you're trying to do is to build a custom view for playing video.

**Comment by ivmilicevic** [comment]
Thank you for detailed reply, I really appreciate it. I think custom scene is bit advanced for scope of this project, but maybe we'll get it working
